Project/Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('<slug>/', views.article_detail, name="detail"),
]

Project/home/urls.py
from . import views
from django.urls import path

urlpatterns = [
   	#path('',views.index),
    path('',views.question_list,name='question_list'),
    path('question/<int:question_id>',views.question_detail, name='question_detail'),
    path('question/<int:question_id>/upvote',views.question_upvote, name='question_upvote'),
    path('question/<int:question_id>/downvote',views.question_downvote, name='question_downvote'),
    path('question/<int:question_id>/answer_upvote/<int:answer_id>',views.answer_upvote, name='answer_upvote'),
    path('question/<int:question_id>/answer_downvote/<int:answer_id>',views.answer_downvote, name='answer_downvote'),
    path('question/add',views.add_question, name='add_question'),
 	path('question/tag/<str:tag>',views.tag_filter, name='tag_filter'),
 	path('question/<int:question_id>/<int:answer_id>',views.edit_answer, name='edit_answer'), 
]

Project/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    # add in author later

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

Project/articles/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Article

def article_list(request):
    articles = Article.objects.all().order_by('date');
    return render(request, 'articles/article_list.html', { 'articles': articles })

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', { 'article': article })

Project/articles/templates/articles/article_detail.html
{% extends 'base.html' %}
{% load static %}
<h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
{% block content %}
<h1><a href="{% url 'articles:list' %}">Blog Lists</a></h1>
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

Project/articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% load static %}


{% block content%}
    Blog Lists
    <div class="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}